/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/copa.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/copa.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_node.geometry} material={materials.material} />
      <mesh geometry={nodes.ball.geometry} material={materials.material} />
      <group position={[0, 0.339, 0]} rotation={[-0.995, 0, -Math.PI / 3]} scale={1.432}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.glass} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.black} />
      </group>
      <mesh geometry={nodes.ETec.geometry} material={materials['Material.001']} position={[-0.007, 0.339, 0.16]} rotation={[Math.PI / 2, 0, 0]} scale={0.2} />
    </group>
  )
}

useGLTF.preload('/copa.glb')
